AcalaNetwork/chopsticks

e2e/__snapshots__/dev.test.ts.snap, e2e/author.test.ts, e2e/dev.test.ts, e2e/helper.ts, src/blockchain/index.ts, src/rpc/dev.ts
=> set storages

configs/kusama.yml, e2e/import-storage/index.test.ts, src/blockchain/storage-layer.ts, src/utils/set-storage.ts
=> able to clear storage map

src/rpc/substrate/state.ts
previous shape is
```
{
result: '0xxxx',
storageDiff: ...
}
```
and we need the actual result.
previously `eth_call` throws `can't decode` error, after the fix it works
=> fix state_call

src/rpc/dev.ts
```
{
"id": 2,
"jsonrpc": "2.0",
"method": "dev_newBlock",
"params": [{"hrmp": { "2034": [{ "send_at": 13740000, "data": "0x000210000400000106540254a37a01cd75b616d63e0ab665bffdb0143c52ae0013000064a7b3b6e00d0a1300000106540254a37a01cd75b616d63e0ab665bffdb0143c52ae0013000064a7b3b6e00d010700f2052a010d010004000101003679d1d8e31d312a55f7ca994773b6a4fc7a92f07d898ae86bad4f3cab303c49" }] }}]
}
```
will generate new block perform XCM transfer
=> able to inject hrmp via dev_newBlock

packages/chopsticks/src/setup.ts
When new pallets are adding in the wasm-override, you can't override their storage currently. This pr swap the order of wasm overriding and storage overwriting
=> override wasm before importing storage

packages/chopsticks/src/cli.ts, packages/chopsticks/src/try-runtime.ts
may be this https://github.com/AcalaNetwork/chopsticks/issues/70 (so only None , no checks filter)
=> try runtime

packages/chopsticks/src/cli.ts, packages/chopsticks/src/run-block.ts, packages/chopsticks/src/setup.ts, packages/chopsticks/src/utils/import-storage.ts
make it possible to override WASM and import storage for run-block command
=> update run-block command

packages/chopsticks/src/server.ts
If connecting to > 5 chains, the current code fails to find ports for all of the chains. There is probably a better fix possible but as a quick fix this is fine
=> try more ports before giving up

packages/chopsticks/src/run-block.ts
closes #329
should always use parent wasm to run current block
=> fix run block

README.md, packages/chopsticks/src/logger.ts, packages/e2e/src/helper.ts, packages/e2e/src/system.test.ts
add `VERBOSE_LOG` to avoid truncate log message so people can copy the whole XCM from logs
=> add VERBOSE_LOG env var

packages/chopsticks/src/plugins/new-block/index.ts, packages/core/src/blockchain/block-builder.ts, packages/core/src/blockchain/txpool.ts, packages/e2e/src/build-block.test.ts
closes: https://github.com/AcalaNetwork/chopsticks/issues/386
Update dev_newBlock to take a unsafeBlockHeight parameter to create new block at a specific block height.
---
**Manual test**
```json
{
"jsonrpc": "2.0",
"id": 1,
"method": "dev_newBlock",
"params": [{
"count": 1,
"unsafeBlockHeight": 3000006
}]
}
```
```json
{
"jsonrpc": "2.0",
"id": 1,
"method": "dev_newBlock",
"params": [{
"count": 2,
"unsafeBlockHeight": 11000006
}]
}
```
=> add unsafeBlockHeight

packages/chopsticks/src/cli.ts, packages/chopsticks/src/context.ts, packages/chopsticks/src/schema/index.ts, packages/core/src/blockchain/index.ts, packages/e2e/src/blocks-save.test.ts, packages/testing/src/index.ts
=> feat: load blocks from db

packages/chopsticks/src/rpc/substrate/author.ts, packages/e2e/src/author.test.ts
closes #375 
Now the rpc's behaviour is the same as normal nodes, and both polkadot.js and chopstick won't crash when submit unsigned tx
=> fix polkadot js got unknown error

.github/workflows/deploy-web-test.yml, .github/workflows/deploy.yml, packages/web-test/package.json, packages/web-test/vite.config.js
closes: https://github.com/AcalaNetwork/chopsticks/issues/395
Tested in my fork, deployed version: https://qiweiii.github.io/chopsticks-1/
=> Deploy web test to github pages

.github/workflows/deploy.yml, .vitepress/config.mts, packages/web-test/index.html
fix: route for docs in deployed version is wrong
tested on my fork: https://qiweiii.github.io/chopsticks/
=> fix deploy docs

packages/core/src/blockchain/block-builder.ts, packages/core/src/blockchain/txpool.ts
helpful for #295 and avoid redundant format when not on trace level logging
=> refactor block builder

packages/core/src/blockchain/index.ts
as mentioned here https://github.com/AcalaNetwork/chopsticks/issues/452#issuecomment-1776005992, limit memory block count for now to mitigate exceed max call stack size
=> reduce default maxMemoryBlockCount

packages/db/src/base-sql.ts, packages/db/src/db/index.ts, packages/db/src/retry.ts
fix this error:
The previous PR #467 missed this case: 2 server initialize connection at the same time
=> retry on sqlite initialize

packages/chopsticks/src/plugins/dry-run/dry-run-preimage.ts, packages/chopsticks/src/plugins/run-block/index.ts, packages/core/src/blockchain/block.ts, packages/core/src/blockchain/inherent/index.ts, packages/core/src/utils/decoder.ts, packages/core/src/utils/index.ts, packages/core/src/utils/time-travel.ts, packages/core/src/wasm-executor/index.ts, packages/e2e/src/time-travel.test.ts
Replay a block and get all the details out from it
=> run block rpc

packages/chopsticks/src/context.ts
In #352, the order of WASM and storage override order introduced in #199 was reverted. I suppose this happened by accident as the inline docs still state WASM override to have order priority. Moreover, it destroys the purpose of WASM override as new pallets cannot override storage.
=> fix: order of wasm and storage overrides

executor/Cargo.lock, executor/src/task.rs, packages/chopsticks/src/plugins/run-block/index.ts, packages/chopsticks/src/utils/generate-html-diff.ts, packages/core/src/blockchain/block-builder.ts, packages/core/src/blockchain/block.ts, packages/core/src/utils/index.ts, packages/core/src/wasm-executor/index.ts
=> support runtime log level

configs/centrifuge.yml
* Adds Centrifuge Config with some conveniences prepared for Alice
* The `wasm-override` and `Sudo` keys are commented out intentionally since the default Centrifuge WASM does not include Sudo
* The WASM including Sudo is custom built, we will expose it in the future
=> feat: add centrifuge config

packages/core/src/blockchain/block-builder.ts
has error when using manta config:
- we have randomness, but don't have `notFirstBlock` yet.
```
root@VM-0-3-ubuntu:~/chopsticks# npx @acala-network/chopsticks@latest --config=configs/manta.yml
Unable to map [u8; 32] to a lookup index
[11:12:58.488] INFO (xcm/766006): Manta Parachain RPC listening on port 8000
/root/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/block-builder.js:116
head.pushStorageLayer().set((0, _index.compactHex)(meta.query.randomness.notFirstBlock()), _storagelayer.StorageValueKind.Deleted);
^
TypeError: meta.query.randomness.notFirstBlock is not a function
at newHeader (/root/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-core/dist/cjs/blockchain/block-builder.js:116:86)
at async buildBlock …
```
=> fix randomness notFirstBlock undefined

executor/src/lib.rs, executor/src/task.rs, packages/core/src/wasm-executor/browser-wasm-executor.js, packages/core/src/wasm-executor/executor.test.ts, packages/core/src/wasm-executor/index.ts, packages/core/src/wasm-executor/node-wasm-executor.js
closes #551
This ensures errors are correctly propagated across wasm boundary
=> Improve error hanlding

configs/acala.yml, configs/karura.yml
would it make sense to bind Alice to the test account we use in all tutorials by default, so we can test EVM+ out of box (currently we need to manually create a config for testing EVM+)
=> bind test account to Alice in Acala config

packages/core/src/utils/index.ts
At Tanssi, we are working on adding support for asynchronous backing. Of course, this involves changing the slot duration from `12000` milliseconds to `6000` milliseconds.
While trying to test some features using chopsticks (like upgrading the on-chain runtime), we are encountering the issue that the network doesn't even start. The reason for this is that at the moment of fetching the slot duration inside `getSlotDuration` function, Tanssi chain metadata doesn't match with any of the current statements.
As Tanssi doesn't make use of Aura or Babe pallets directly, but instead of the AsyncBacking pallet ([implemented](https://github.com/Moonsong-Labs/moonkit/blob/main/pallets/async-backing/src/lib.rs) in Moonkit repo), it would be nice to have an extra statement that checks for the …
=> Tanssi: Add support for `expectedBlockTime` of async backing pallet

configs/altair.yml
Adds config for Kusama parachain Altair (canary of Centrifuge Chain)
=> feat: add Altair config

configs/centrifuge.yml
Improves mocks for Centrifuge config I have been using locally for a while:
* Sets log level to debug per default
* Increases Alice funds (native and foreign assets)
* Adds funds for Bob and Charlie
* Adds example mocks for proxy, pool admin and oracle feeder
=> chore: improve centrifuge config mocks

configs/moonbase-alpha.yml, configs/moonbeam.yml, configs/moonriver.yml
Moonbeam, Moonriver and Moonbase Alpha no longer use some of the collective pallets in favor of other collectives
=> Fix Collective Pallets Moonbeam

configs/acala.yml, configs/astar.yml, configs/basilisk.yml, configs/bifrost.yml, configs/hydradx.yml, configs/interlay.yml, configs/karura.yml, configs/khala.yml, configs/phala.yml, configs/polkadot.yml
This was very valuable when debugging XCM error messages. It was nice that it was the default already for Centrifuge, so seems like a good idea to make it the default for several other chains as well.
=> `runtime-log-level: 5` for most chains

README.md, packages/chopsticks/src/cli.ts, packages/chopsticks/src/plugins/index.ts, packages/chopsticks/src/rpc/index.ts, packages/e2e/src/rpc-extention-methods.test.ts, packages/e2e/src/rpc-methods-test-scripts.js
This allows us to directly use the CLI to load scripts and extend our RPC methods. Others can easily extend rpc methods by using npx cli.
Here's an example:
`npx @acala-network/chopsticks@latest --rpc-methods=https://example.com/test.js`
`npx @acala-network/chopsticks@latest --rpc-methods=./test.js`
The script: 
``` javascript
return {
async dev_testRpcMethod1(context, params, subscriptionManager) {
console.log('dev_testRpcMethod 1')
},
async dev_testRpcMethod2(context, params, subscriptionManager) {
console.log('dev_testRpcMethod 2')
},
}
```
=> feat: load rpc additional methods by cli

configs/darwinia.yml
I have successfully used this config to test sending Darwinia RING to HydraDX. I didn't personally test sending USDT and PINK, but confirmed the entries in the AssetHub registry.
=> add configs/darwinia.yml

configs/bifrost-polkadot.yml
Bifrost Kusama and Bifrost Polkadot chains need different configs. Previously, running with `bifrost.yml` would emulate Kusama Bifrost parachain, but had token config for Polkadot tokens. Therefore split them and clean that up.
Tested by running Chopsticks and using p.js to verify tokens in the account.
=> separate Bifrost-Polkadot config from KSM Bifrost-Polkadot

configs/altair.yml, configs/centrifuge.yml
* Update RPC endpoints
* Increase default funds
=> refactor: improve Centrifuge & Altair configs

packages/core/src/blockchain/inherent/parachain/validation-data.ts, packages/core/src/blockchain/inherent/timestamp.ts, packages/core/src/utils/index.ts, packages/e2e/src/connect-horizontal.test.ts
Slot injected into aura digests needs to be calculated rather than incrementing by one
This will make it possible to transition from 12s block to 6s block time
=> support async transition

packages/chopsticks/src/server.ts, packages/e2e/src/http.test.ts
Initial bit of work for #801 
This makes id handling spec-compliant by [JSON-RPC 2.0](https://www.jsonrpc.org/specification). Notable changes:
- The `id` can now be parsed as a number, string, null or undefined
- If the `id` is a number, it must be an integer.
- The `id` from error responses is now correct:
- If it was while parsing the message, then it's `null`.
- If it was while handling a request, then it's the same request id as that request.
- It handles notifications correctly: if the `id` is undefined, no response is returned. 
~~I couldn't find a good place to add tests for these cases - please let me know if you want me to add some, or if you need anything else.~~
I could find the test file, `e2e/src/http.test.ts`
=> make json-rpc server id handling spec-compliant

configs/polkadot-coretime.yml
Another trivial one to add the config for Polkadot Coretime.
RPC is live even though the chain is not yet making blocks
=> Add Coretime Polkadot config

packages/core/src/blockchain/txpool.ts
when block building mode is manual, it should be manual
=> no auto block in manual mode

packages/core/src/rpc/rpc-spec/index.ts, packages/core/src/rpc/rpc-spec/transaction_v1.ts, packages/e2e/src/helper.ts, packages/e2e/src/rpc-spec.test.ts
This PR adds the `transaction_v1` group of functions of the JSON RPC interface spec into the RPC server.
It's fairly simple, since it's only two functions: one starting a broadcast, and the other to stop it.
We'll be missing only one last group to make it fully compatible with papi, the `chainSpec` one. Looks fairly simple, will work on it next and raise as a separate PR.
=> feat: add transaction_v1 group of functions

packages/core/src/rpc/rpc-spec/chainSpec_v1.ts, packages/core/src/rpc/rpc-spec/index.ts, packages/e2e/src/__snapshots__/rpc-spec.test.ts.snap, packages/e2e/src/rpc-spec.test.ts
Last missing group of functions to provide support with papi, so this closes #801 
I may need help with the `genesisHash` function - I thought this would be available on the chain object directly, but it's not.
I called `getBlockHash(0)`, which seems to get the job done, it seems to work when starting from genesis and from a wsUrl, but the types say it might return null. I couldn't find any case where this happens, but I'm also not sure what to do in this case.... any ideas?
=> feat: add chainSpec_v1 group of functions

packages/core/src/blockchain/inherent/parachain/validation-data.ts, packages/core/src/blockchain/txpool.ts, packages/core/src/rpc/dev/new-block.ts, packages/core/src/utils/proof.ts, packages/e2e/src/build-block.test.ts, packages/e2e/src/build-parachain-block.test.ts
Adds a solution for this issue: https://github.com/AcalaNetwork/chopsticks/issues/757
The changes in this PR add a new parameter field `relayChainStateOverrides` to `dev_newBlock` RPC. The objective of this new field is to give more flexibility to the user and allow custom relay chain state when creating new blocks.
=> feat(dev_newBlock): Adds option to override relaychain state

configs/stagelight.yml, packages/core/src/blockchain/inherent/parachain/nimbus-author-inherent.ts
This PR moves the mock of `author noting` before the `kick_off_authorship` inherent checks. We have a new chain in which we only run the author noting inherent but not the `kick_off_authorship` inherent, which would fail before this PR. This should not affect any of the other chains as we are only mocking the storage that verifies on_finalize that the inherent has run.
Additionally, I added a new config for the new chain, which we are calling stagelight. this is for now just the stagenet version of a testnet that will be launched in a couple of weeks, once we launch it I will make a PR putting the testnet config file
=> Rework author noting inherent mock and stagelight config

configs/ajuna.yml, configs/crust.yml, configs/frequency.yml, configs/hydradx.yml, configs/invarch.yml, configs/kilt.yml, configs/mythos.yml, configs/pendulum.yml, configs/polimec.yml, configs/subsocial.yml
* add configs for Ajuna, Crust, Frequency, InvArch, Kilt, Mythos, Pendulum, Polimec, Subsocial
* add more tokens to Hydration registry
=> add initial config files for 9 chains

packages/core/src/rpc/rpc-spec/chainHead_v1.ts, packages/e2e/src/chainHead_v1.test.ts
I've added pagination by performing storage queries with 1000 values at a time, then storing the pending requests on the "callbacks" map we had, which I have repurposed to better represent the state of each follow subscription.
I also added a test by querying a storage query that has more than 1000 values, but without being too much. I've found System.BlockHash has 1201 entries, so I thought that's a good candidate. Let me know if I should change this for a better alternative.
Closes #837
=> feat(chainHead_v1): operationWaitingForContinue and chainHead_v1_continue

packages/core/src/rpc/substrate/chain.ts, packages/e2e/src/chain.test.ts
=> Add `archive_unstable_hashByHeight` as alias to `chain_getBlockHash`

package.json, packages/chopsticks/package.json, packages/chopsticks/src/utils/fetch-storages.test.ts, packages/chopsticks/src/utils/fetch-storages.ts, packages/core/package.json, packages/core/src/blockchain/get-keys-paged.test.ts, packages/core/src/blockchain/storage-layer.ts, packages/db/package.json, packages/testing/package.json, packages/utils/package.json, yarn.lock
Old key iteration doesn't guarantee correct key iteration and code implementation was a mess (more a workaround).
New implementation is simpler (a bit slower) but guarantee to lookup all layers to find best possible next key
=> refactor key iteration

README.md
This PR takes the introduction paragraph from the Moonbeam docs and places it at the head of this repo's README.
---
I found this repo from a link in a group chat, but struggled to figure out what this repo was actually for. The text "Create parallel reality of your Substrate network" didn't clear anything up. 
After a bit of searching I found the Moonbeam docs with a page detailing how to use Chopsticks with Moonbeam: https://docs.moonbeam.network/builders/substrate/dev-env/chopsticks/. I figured that intro would work well here too.
**Repo maintainers: Feel free to ignore this PR if you think it isn't necessary. You won't hurt my feelings.**
=> Adds a simple project introduction to the README.

packages/core/src/rpc/rpc-spec/chainHead_v1.ts, packages/e2e/package.json, packages/e2e/src/chainHead_v1.test.ts, packages/e2e/src/helper.ts, yarn.lock
Addresses #870
This gives support for Polkadot-API's `query.watchEntries()`, which subscribes to the storage using `closestDescendantMerkleValue` to detect changes.
As discussed in #870, chopsticks doesn't work with the merkle tree directly, but with storage diffs.
As polkadot-api doesn't really need the correct hash, but just that the value returned is different when any storage value under that branch changes, this implementation fakes the merkleValue to be based on a counter of how many changes were detected for that branch.
I have added a test with the top-level client of polkadot-api (now that it doesn't require codegen/descriptors to run) and it seems to be working as expected.
=> feat(chainHead_v1): fake closestDescendantMerkleValue

packages/core/src/api.ts, packages/core/src/genesis-provider.ts, packages/core/src/setup.ts, packages/e2e/src/connect-horizontal.test.ts
closes #841
when no block specified, instead of using best head, use finalized head instead. this ensures we won't be building new blocks on a fork, which will be inaccessible after it is purged
=> default to finalzied head

configs/energywebx.yml, configs/pex.yml
Add specs for Energy Web X mainnet and Energy Web X on the Paseo testnet for integration into Chopstick.
=> Add: Energy Web X parachain mainnet and testnet config file

packages/core/src/blockchain/get-keys-paged.test.ts, packages/core/src/blockchain/storage-layer.ts, packages/core/src/utils/index.ts, packages/e2e/src/author-inherent-mock.test.ts, vitest.config.mts
closes #897
this don't eliminate getKeysPaged call which requires we store fetch ranged in db but should significantly reduce RPC requests with a prefetched db
=> avoid fetch storages already in db

configs/paseo.yml
This adds a paseo.yml file so that a paseo chopsticks instance can be spawned with `chopsticks -c paseo`.
I'm using Dwellir RPC, I'm not sure if that's acceptable, and setting ALICE as sudo key (similar to other config files for test networks)
=> feat: add paseo config

packages/chopsticks/src/context.ts, packages/chopsticks/src/schema/index.ts, packages/chopsticks/src/schema/options.test.ts, packages/core/src/setup.ts, packages/e2e/src/helper.ts
Closes #906
Closes #896
**Summary of Changes**:
- Added an RPC timeout option to the setup and context configuration.
- Updated the `setupContext` function to include the RPC timeout option.
- Modified the `WsProvider` constructor to accept the RPC timeout option.
**Highlights of Changed Code**:
- The `setupContext` function now includes the `rpcTimeout` option in its configuration.
- The `WsProvider` constructor has been updated to accept the `rpcTimeout` option.
**Additional Information (if needed)**:
- The RPC timeout option allows for more control over the setup and context configuration.
- The changes are backwards compatible and do not introduce any breaking changes.
=> Add RPC Timeout Option to Setup and Context Configuration

configs/statemine.yml, configs/statemint.yml
`npx @acala-network/chopsticks@latest -c statemint` is currently not working.  
Seems to be Dwellir renamed the RPC.
=> Update statemin* RPCs

packages/chopsticks/src/context.ts, packages/chopsticks/src/schema/index.ts, packages/chopsticks/src/schema/options.test.ts, packages/core/src/blockchain/index.ts, packages/core/src/setup.ts
we want to disable it in ecosystem tests to avoid caching blocks produced in tests
=> feat: add saveBlocks option to setup and blockchain configurations

packages/core/src/blockchain/block.ts, packages/core/src/blockchain/get-keys-paged.test.ts, packages/core/src/blockchain/storage-layer.ts, packages/core/src/rpc/rpc-spec/storage-common.ts
I realised that when doing a `descendantValues` query with chopsticks, this one does a `state_getKeysPaged` followed by individual `state_getStorage` for each of the values. This makes those queries go quite slow.
When I implemented chainHead_v1, the `block` API didn't offer a way to query many values at once, so that's what I used.
This PR adds a `block.getMany()` to fetch multiple values at once. This had to be implemented on the storage-layer as well.
~~TODO review tests.~~ Please let me know if this feature is something you want as well, or if there are other implications I haven't thought of, since I haven't opened a discussion/issue before :'D
Kind-of related, this also allows to optimise certain operations that take a long time: I managed to speed up building the initial block from …
=> feat: add getMany to storage queries
