e2e/__snapshots__/author.test.ts.snap, e2e/__snapshots__/chain.test.ts.snap, e2e/storage.test.ts, executor/Cargo.lock, executor/src/lib.rs, executor/src/main.rs, executor/src/runner_api.rs, executor/src/task.rs, src/blockchain/inherents.ts, src/blockchain/txpool.ts
=> support relaychain

executor/src/task.rs
=> able to disable signature verification

karura-rococo.yml, package.json, src/blockchain/txpool.ts, src/index.ts, yarn.lock
=> accept config from config file

e2e/helper.ts, e2e/mock-signature.test.ts, executor/src/task.rs, src/task.ts
=> allow to run wasm anyway

e2e/dev.test.ts, e2e/helper.ts, src/rpc/dev.ts
=> fast forward

e2e/helper.ts, src/blockchain/inherents.ts, src/index.ts
Computes the validation data index in the extrinsics list instead of hard coding it
Fixes #92
=> Adds support for validation data different indexes

README.md
=> Added link to Moonbeam documentation site on Chopsticks

executor/Cargo.lock, executor/pkg/package.json, executor/src/proof.rs, executor/src/task.rs, package.json, packages/chopsticks/src/blockchain/block.ts, packages/chopsticks/src/blockchain/index.ts, packages/chopsticks/src/cli.ts, packages/chopsticks/src/dry-run-preimage.ts, packages/chopsticks/src/dry-run.ts, packages/chopsticks/src/executor.ts, packages/chopsticks/src/genesis-provider.ts, packages/chopsticks/src/run-block.ts, packages/chopsticks/src/schema/index.ts, packages/chopsticks/src/setup.ts
awaiting https://github.com/smol-dot/smoldot/pull/276
=> get runtime logs from vm

configs/nodle-eden.yml
=> chore: add Nodle's Eden parachain config

configs/acala.yml, configs/basilisk.yml, configs/hydradx.yml, configs/karura.yml, configs/kusama.yml, configs/mandala.yml, configs/mangata.yml, configs/moonbase-alpha.yml, configs/moonbeam.yml, configs/moonriver.yml, configs/nodle-eden.yml, configs/picasso-kusama.yml, configs/polkadot.yml, configs/rococo.yml, configs/statemine.yml, packages/chopsticks/package.json, packages/chopsticks/src/cli.ts, packages/chopsticks/src/schema/index.ts
=> allow specify block number from env

configs/astar.yml, configs/shiden.yml
Include 100'000 USDT, DOT and ASTR tokens for Polkadot
and 100'000 USDT, KSM and SDN tokens for Kusama
=> Configs for Astar and Shiden

configs/astar.yml, configs/shiden.yml
Will help others extend this config when needed.
=> comments to Astar`s assets

configs/polkadex.yml
=> Created polkadex.yml

configs/bifrost.yml, configs/imbu.yml, configs/mangata.yml
* Add more tokens in mangata config.
* Update endpoint
* Log level to get node logs
* Create bifrost.yml
* Create imbu.yml
=> a few config changes

README.md, configs/hydradx.yml, configs/interlay.yml, configs/tinkernet.yml
I've added support for Interlay, Tinkernet, and included balances for all defined assets. I've also extended HydraDX's config to include all assets there.
=> Adding support for Interlay, Tinkernet, and update to the HydraDX configuration

configs/hydradx.yml
In the HydraDX Config, I added Alice as Council and TechCommittee to be able to fast track proposals for testing.
Also bumped Alice so she can be a bit more of a whale :)
=> Added Council and TechCommittee to HydraDX Config

configs/shibuya.yml, configs/shiden.yml
Adds config for `Shibuya` testnet.
=> Add Shibuya Config

packages/chopsticks/src/blockchain/block-builder.ts, packages/chopsticks/src/blockchain/head-state.ts, packages/chopsticks/src/blockchain/index.ts, packages/chopsticks/src/cli.ts, packages/chopsticks/src/schema/index.ts, packages/chopsticks/src/setup.ts, packages/e2e/src/max-memory-block-count.test.ts, packages/testing/src/index.ts
=> Max memory block count

packages/chopsticks/src/blockchain/index.ts
This reverts commit 88037210f772e11eb64c7014187c97f73e1650b7.
=> Revert "improve register block (#360)"

packages/chopsticks/src/rpc/substrate/chain.ts, packages/core/src/blockchain/index.ts, packages/core/src/db/entities.ts
closes: https://github.com/AcalaNetwork/chopsticks/issues/376
=> fix header.toJSON is not a function

.vitepress/config.mts, packages/chopsticks/src/rpc/shared.ts, packages/chopsticks/src/rpc/substrate/author.ts, packages/chopsticks/src/rpc/substrate/chain.ts, packages/chopsticks/src/rpc/substrate/index.ts, packages/chopsticks/src/rpc/substrate/payment.ts, packages/chopsticks/src/rpc/substrate/state.ts, packages/chopsticks/src/rpc/substrate/system.ts, packages/chopsticks/src/rpc/types.ts, packages/chopsticks/src/types.ts, packages/core/src/api.ts
=> add rpc types and docs

configs/tinkernet.yml
Updates the Tinkernet RPC in configs/tinkernet.yml
=> Update Tinkernet RPC

packages/chopsticks/src/rpc/substrate/author.ts
I _think_ that this is all that needs doing, but please correct me if I've missed something :) Locally I couldn't get the tests running properly, so I'm hoping CI will have more luck! You're welcome to throw this away and make a new PR if it turns out that that's easier for you!
Closes #304
=> camelCase TX event names

packages/chopsticks/src/context.ts
closes: https://github.com/AcalaNetwork/chopsticks/issues/417
- log resumed block number & hash when resumed
- in the case the provided block number / hash is not found, log error and exit
=> improve resume

packages/chopsticks/src/server.ts, packages/e2e/src/__snapshots__/batch-request.test.ts.snap, packages/e2e/src/batch-request.test.ts, packages/testing/src/index.ts
=> support batch request

packages/db/src/base-sql.ts, tsconfig.base.json
closes #435
Seems cannot always reproduce the sqlite_busy error in tests, so didn’t add one
=> handle sqlite busy

packages/core/src/wasm-executor/index.ts
bun also have global `Worker` so need another way to detect env
=> improve worker

packages/chopsticks/package.json, packages/core/package.json, packages/db/package.json, packages/testing/package.json, yarn.lock
fix #533
using [depcheck](https://www.npmjs.com/package/depcheck) find missing dependencies, and added them
=> add missing deps

configs/kabocha.yml
I'd like to add Kabocha, please.  Is it as simple as this, or do I need to do more things before this can be merged?
=> Add basic config file for Kabocha

configs/encointer-kusama.yml, configs/integritee-kusama.yml, configs/integritee-polkadot.yml, configs/integritee-rococo.yml
tested all and working
such a nice tool :+1:
=> add integritee and encointer configs

executor/src/lib.rs, executor/src/task.rs, packages/core/src/genesis-provider.ts, packages/core/src/wasm-executor/index.ts
ClosestDescendantMerkleValue impl is wrong but also not used
=> remove unused method

packages/chopsticks/src/plugins/run-block/cli.ts
read runtime log level from configs
=> fix run block log level

packages/core/src/rpc/substrate/state.ts
=> alias state_getStorageAt

configs/neuroweb-testnet.yml, configs/neuroweb.yml
- Added configs for NeuroWeb and NeuroWeb Testnet
=> Add NeuroWeb and NeuroWeb Testnet to configs

configs/bifrost.yml, configs/centrifuge.yml, configs/hydradx.yml, configs/interlay.yml, configs/phala.yml
* remove `sudo` pallet from Phala chain config
* Add all ForeignAssets and LendTokens for Interlay chain config
* Add all Token2, VToken2, and VSToken2 for Bifrost chain config
* Add recent tokens registered on HydraDX in chain config
* reduce any iBTC/WBTC tokens to 21 million with 8 decimal points
=> remove Phala sudo; Add Interlay/Bifrost/Hydra tokens

executor/src/task.rs, packages/e2e/src/state.test.ts
=> fix: runtime call not found

configs/kusama-coretime.yml
Adds a simple Kusama coretime config
=> feat: add simple kusama coretime config

executor/package.json, packages/chopsticks/package.json, packages/core/package.json, packages/db/package.json, packages/testing/package.json, packages/utils/package.json, yarn.lock
=> fix deps and update version

.github/workflows/ci.yml, README.md, executor/package.json, package.json, packages/chopsticks/package.json, packages/chopsticks/src/plugins/fetch-storage/cli.ts, packages/chopsticks/src/utils/fetch-storages.ts, packages/core/package.json, packages/db/package.json, packages/testing/package.json, packages/utils/package.json, yarn.lock
- check deps with `depcheck`
- fixed some missing/unused deps
close #772
=> ci with depcheck

packages/chopsticks/src/cli.ts
#788
new error message:
```
Error: Bad argv
at processArgv (/Users/qiweiyang/GitHub/chopsticks/packages/chopsticks/src/cli.ts:28:13) {
[cause]: { 'runtime-log-level': [ 'Expected number, received string' ] }
}
```
=> flatten zod errors

configs/polkadot-people.yml
Trivial PR to add a spec for Polkadot People Chain (now live)
=> Add Polkadot People Chain config

packages/chopsticks/src/context.ts, packages/chopsticks/src/schema/index.ts, packages/chopsticks/src/schema/options.test.ts, packages/e2e/src/connect-horizontal.test.ts
Alias genesis to chain-spec to align the terms
=> support chain-spec

packages/core/src/genesis-provider.ts
=> add state_queryStorageAt impl for genesis provider

packages/core/src/blockchain/inherent/parachain/validation-data.ts, packages/core/src/blockchain/txpool.ts, packages/core/src/rpc/dev/new-block.ts, packages/e2e/src/build-parachain-block.test.ts, packages/e2e/src/dev.test.ts, packages/utils/package.json, packages/utils/src/index.ts, yarn.lock
=> dev_newBlock support relayParentNumber

configs/laos.yml
Hi, [Laos](https://github.com/freeverseio/laos) developer here. 
We've been recently using chopsticks in our tests and realized that LAOS isn't listed in the configs folder, so we'd like to have a dedicated file if possible. 
Thank you so much
=> Feature: Add LAOS config file to configs folder

configs/bifrost-polkadot.yml, configs/bifrost.yml
Default config RPCs were failing so switched them to Dwellir's
=> Updates Bifrosts RPCs

README.md
Mentioned in https://github.com/AcalaNetwork/chopsticks/issues/886 .
=> Update `README` regarding storage related features

packages/core/src/wasm-executor/index.ts
=> add task id to make debugging eaiser

packages/utils/src/index.ts
=> expose saveBlock to SetupOption

configs/xcavate.yml
Added chopstic config for xcavate chain
=> xcavate chopstic config

packages/e2e/src/__snapshots__/hrmp.test.ts.snap, packages/e2e/src/hrmp.test.ts, yarn.lock
* Update HRMP messages with something recent
* Run `yarn dedupe`
=> update e2e tests hrmp

packages/core/src/blockchain/inherent/parachain/validation-data.ts
it should be empty https://github.com/AcalaNetwork/chopsticks/pull/941#discussion_r2200094876
=> hashed_messages should be empty

packages/testing/src/check.ts
This PR introduces a `noRedact` flag to completely disable redaction in `RedactOptions`, adds support for per-key redaction overrides, and refactors the check setup to use a centralized configuration system.
**Summary of Changes**:
- Updated `RedactOptions` to support a `noRedact` flag and `overrides` for key-specific redaction rules
- Refactored redaction logic to handle nested objects and key-specific configurations
- Introduced `setupCheck` function for centralized configuration of check utilities
- Simplified `withExpect` to use the new centralized setup
**Highlights of Changed Code**:
- `RedactOptions` now uses a union type with optional `noRedact: true` to bypass all redaction
- Added `overrides` field in `RedactOptions` for granular per-key configurations
- Created recursive …
=> Enhance Redaction Options and Centralize Check Configuration

packages/core/src/api.ts, packages/core/src/blockchain/storage-layer.ts
Addresses #961 
I've set the batch size for any remote getStorageBatch to 300, but also making each batch to get a similar size (so a 301 operation will have two batches, with sizes 151 and 150)
=> fix: split getStorageBatch into smaller batches
